title: Kubeflow on OKE
schemaVersion: 1.1.0
version: "20211108"
locale: "en"
groupings:
  - title: "SSH Key"
    variables:
      - ssh_provided_public_key
  - title: "Availabilty Domain"
    variables:
      - availability_domain
  - title: "VCN Options"
    variables:
      - useExistingVcn
      - myVcn
      - vcn_dns_label
      - custom_cidrs
      - VCN_CIDR
      - edge_cidr
      - private_cidr
      - fss_cidr
  - title: "OKE Cluster Options"
    variables:
      - create_new_oke_cluster
      - cluster_name
      - kubernetes_version
      - cluster_endpoint_config_is_public_ip_enabled
      - OKESubnet
      - existing_oke_cluster_id
  - title: "OKE Kubeflow Pool Configuration"
    variables:
      - kubeflow_node_pool_name
      - kubeflow_node_pool_size
      - nodepool_image_version
      - kubeflow_node_pool_shape
      - node_pool_node_shape_config_memory_in_gbs
      - node_pool_node_shape_config_ocpus

  - title: "Bastion Configuration"
    variables:
      - public_edge_node
      - bastion_name
      - bastion_shape
      - edgeSubnet
  - title: "File System Configuration"
    variables:
      - create_mount_target
      - FssSubnet
  - title: "Kubeflow Configuration"
    variables:
      - kustomize_version
      - kubeflow_version
      - kubeflow_password
      - reserved_public_ip
      - configure_oracle_auth
      - oci_domain
      - oci_client_id
      - oci_client_secret

  - title: "Pre-Defined"
    variables:
      - region
      - compartment_ocid
      - tenancy_ocid
      - user_ocid
      - private_key_path
      - fingerprint
      - oci_service_gateway
      - cluster_options_add_ons_is_kubernetes_dashboard_enabled
      - cluster_options_admission_controller_options_is_pod_security_policy_enabled
      - OELImageOCID
      - service_port
      - endpoint_subnet_id
    visible: false

variables:
  ssh_provided_public_key:
    type: string
    title: "SSH Public Key"
    description: "Copy/Paste the contents of your SSH Public Key"
    required: true
    default: ""

  create_mount_target:
    type: boolean
    title: "Create Mount Target"
    description: "It will create a mount target and Kubeflow will use File System as default storage"
    default: "false"

  create_new_oke_cluster:
    type: boolean
    title: "Create OKE Cluster"
    description: "Check to deploy a new OKE cluster.  If you do not create an OKE cluster you must provide the OCID of an existing one."
    default: "true"

  existing_oke_cluster_id:
    type: string
    title: "Existing OKE Cluster ID"
    description: "Input the existing OKE cluster ID here for deployment."
    visible:
      not:
        - create_new_oke_cluster

  cluster_endpoint_config_is_public_ip_enabled:
    type: boolean
    title: "Create Public Endpoint"
    description: "By default this template will create a secure Kubernetes API endpoint which is on a private subnet accessible only inside the VCN.  By checking this box, you choose to deploy the cluster to a PUBLIC subnet and create a PUBLICLY ACCESSIBLE endpoint."
    default: false
    visible: create_new_oke_cluster

  kubernetes_version:
    type: enum
    enum:
      - "v1.29.1"
      - "v1.26.2"
      - "v1.26.7"
    title: "Kubernetes Version"
    description: "Choose the version of Kubernetes to deploy"
    required: true
    default: "v1.29.1"
    visible: create_new_oke_cluster

  nodepool_image_version:
    type: string
    title: Node Pool Image Version
    description: "Oracle Linux version only"
    default: "7.9"
    required: false

  cluster_name:
    type: string
    title: "OKE Cluster Name"
    description: "Name the OKE Cluster"
    required: "true"
    default: "kubeflow-cluster"
    visible: create_new_oke_cluster

  useExistingVcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Click to use existing VCN, otherwise VCN and Subnets will be created"
    required: true
    default: false

  myVcn:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select Existing VCN"
    dependsOn:
      compartmentId: compartment_ocid
    visible: useExistingVcn
    required: true

  custom_cidrs:
    type: boolean
    title: "Customize Network CIDRS"
    description: "Click to customize CIDR ranges, only applicable when creating VCN as part of deployment"
    required: true
    default: false
    visible:
      not:
        - useExistingVcn

  OKESubnet:
    type: oci:core:subnet:id
    title: "OKE Subnet"
    description: "Select Subnet for OKE cluster"
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: myVcn
    visible: useExistingVcn
    required: true

  edgeSubnet:
    type: oci:core:subnet:id
    title: "Edge Subnet"
    description: "Select Subnet for Bastion.  If using remote exec, ensure that this is a public subnet or deployment will fail."
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: myVcn
    visible: useExistingVcn
    required: true

  FssSubnet:
    type: oci:core:subnet:id
    title: "Mount Target Subnet"
    description: "Select Subnet for Mount Target.  This is the subnet where the Mount Target for File System."
    dependsOn:
      compartmentId: compartment_ocid
      vcnId: myVcn
    visible: useExistingVcn
    required: true

  availability_domain:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "Select AD"
    dependsOn:
      compartmentId: compartment_ocid
    required: true

  VCN_CIDR:
    type: string
    title: "VCN CIDR"
    description: "Customize VCN top level CIDR"
    visible: custom_cidrs

  edge_cidr:
    type: string
    title: "Edge Subnet CIDR"
    description: "Customize Edge Subnet CIDR, ensure this fits in VCN CIDR range."
    visible: custom_cidrs

  private_cidr:
    type: string
    title: "Private Subnet CIDR"
    description: "Customize Private Subnet CIDR, ensure this fits in VCN CIDR range."
    visible: custom_cidrs

  fss_cidr:
    type: string
    title: "Mount Target Subnet CIDR"
    description: "Customize Mount Target Subnet CIDR, ensure this fits in VCN CIDR range."
    visible: custom_cidrs

  vcn_dns_label:
    type: string
    title: "VCN DNS Label"
    description: "Set the VCN DNS label to be used when creating VCN.  Default is 'kubeflowvcn' which sets the VCN domain to 'kubeflowvcn.oraclevcn.com'"
    visible:
      not:
        - useExistingVcn

  kubeflow_node_pool_name:
    type: string
    title: "Kubeflow Node Pool Name"
    description: "Define the node pool name, no spaces"
    required: true
    visible: create_new_oke_cluster

  kubeflow_node_pool_shape:
    type: oci:core:instanceshape:name
    title: "Kubeflow Node Pool Shape"
    description: "Define node pool shape"
    required: true
    visible: create_new_oke_cluster
    dependsOn:
      compartmentId: compartment_ocid
    default: "VM.Standard2.4"


  kubeflow_node_pool_size:
    type: int
    title: "Kubeflow Node Pool size"
    description: "Enter a value, minimum 1"
    min: 1
    default: 1
    required: true
    visible: create_new_oke_cluster

  kubeflow_namespace:
    type: string
    title: "Kubeflow Namespace"
    default: "kubeflow"
    visible: false

  kube_label:
    type: string
    title: "Kube Label"
    default: "kubeflow"
    visible: false

  bastion_name:
    type: string
    title: "Bastion Name"
    default: "bastion"
    required: true

  bastion_shape:
    type: oci:core:instanceshape:name
    title: "Bastion Instance Shape"
    dependsOn:
      compartmentId: compartment_ocid
    default: "VM.Standard2.1"
    required: true
  
  bastion_shape_config_ocpus:
    type: string
    visible: false

  bastion_shape_config_memory_in_gbs:
    type: string
    visible: false

  public_edge_node:
    type: boolean
    title: "Deploy Bastion to Public Subnet"
    default: true
    required: true

  kubeflow_password:
    type: string
    title: "Default password for Kubeflow Login"

  reserved_public_ip:
    type: string
    title: "Input an existing Reserved Public ip to be the point of access for Kubeflow"
    required: true

  configure_oracle_auth:
    type: boolean
    title: "Configure authentication with Oracle IDCS"
    required: true
    default: false

  oci_domain:
    type: string
    title: "OCI Identity Domain URL"
    description: "This URL should be the issuer when accessing DomainUrl.well-known/openid-configuration. Don't forget to add / at the end."
    default: "<https://idcs-xxxxxxxxxxxxxxxxxxxxxx.identity.oraclecloud.com>/"
    visible: configure_oracle_auth
    required: true

  oci_client_id:
    type: string
    title: "OCI Integrated Application Client ID"
    visible: configure_oracle_auth
    required: true

  oci_client_secret:
    type: string
    title: "OCI Integrated Application Client Secret"
    visible: configure_oracle_auth
    required: true

